//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetflixPrjeq05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contenu
    {
        public int id { get; set; }
        public string Description { get; set; }
        public string Affiche { get; set; }
        public Nullable<decimal> Cote_moyenne { get; set; }
        public Nullable<int> Nombre_de_Cote { get; set; }
        public string Status { get; set; }
        public Nullable<int> Budget { get; set; }
        public string Titre_Original { get; set; }
        public Nullable<System.DateTime> Date_de_sortie { get; set; }
        public Nullable<int> Duree { get; set; }
    }
}
