//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetflixPrjeq05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saison
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Saison()
        {
            this.Contenu = new HashSet<Contenu>();
        }
    
        public int SaisonId { get; set; }
        public int SerieId { get; set; }
        public int NoSaison { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contenu> Contenu { get; set; }
        public virtual Serie Serie { get; set; }
    }
}
